<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.5</version>
        <relativePath/>
    </parent>

    <groupId>br.com.bradesco.kit.bff</groupId>
    <artifactId>kbnt-srv-in-cartao-credito</artifactId>
    <version>0.2.0-SNAPSHOT</version>
    <name>kbnt-srv-in-cartao-credito</name>
    <description>Servico Bradesco Expresso</description>
    <organization>
        <name>Bradesco</name>
    </organization>
    <packaging>jar</packaging>

    <!-- Spring Boot - Version Properties -->
    <!-- PROCURAR REUSAR MAPEAMENTO DE VERSAO PROPERTIES DO SPRING BOOT -->
    <!-- https://docs.spring.io/spring-boot/docs/2.7.7/reference/html/dependency-versions.html#appendix.dependency-versions.properties -->
    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mapstruct-version>1.5.3.Final</mapstruct-version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven-dependency-plugin.version>3.5.0</maven-dependency-plugin.version>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
        <okhttp.version>4.10.0</okhttp.version>
        <!-- sonar.coverage.exclusions - Configurar APENAS o que nao faz sentido ser considerado no Sonar Coverage -->
        <sonar.coverage.exclusions>
            src/main/java/br/com/bradesco/kit/bff/adapter/**/*,
            src/main/java/br/com/bradesco/kit/bff/config/**/*,
            src/main/java/br/com/bradesco/kit/bff/Application.java
        </sonar.coverage.exclusions>
        <json.version>20220924</json.version>
        <bradesco.enge.logcloud.version>1.0.0.rc.0</bradesco.enge.logcloud.version>
        <springfox.swagger.version>3.0.0</springfox.swagger.version>
        <frwk-lib-connector-cws-sb.version>0.0.5</frwk-lib-connector-cws-sb.version>
        <enge-lib-mbtoken-spring-starter.version>1.0.0.RC0</enge-lib-mbtoken-spring-starter.version>
        <embedded-redis.version>0.7.3</embedded-redis.version>
        <springdoc.version>1.6.14</springdoc.version>
        <nimbus-jose-jwt.version>9.28</nimbus-jose-jwt.version>
        <lombok.version>1.18.26</lombok.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <oauth2-oidc-sdk.version>10.9</oauth2-oidc-sdk.version>
        <feign-httpclient.version>12.3</feign-httpclient.version>
        <modelmapper.version>3.0.0</modelmapper.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>


        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10.1</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>com.vaadin.external.google</groupId>
                    <artifactId>android-json</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-contract-stub-runner</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.15.2</version>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>1.9.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>${springfox.swagger.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.restdocs</groupId>
            <artifactId>spring-restdocs-mockmvc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${json.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>br.com.bradesco.enge.logcloud</groupId>
            <artifactId>enge-lib-logcloud-spring-starter</artifactId>
            <version>${bradesco.enge.logcloud.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.modelmapper</groupId>
            <artifactId>modelmapper</artifactId>
            <version>${modelmapper.version}</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>kbnt-srv-in-cartao-credito</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${project.parent.version}</version>
                <configuration>
                    <fork>true</fork>
                    <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
                    <mainClass>br.com.bradesco.kit.bff.Application</mainClass>
                    <layers>
                        <enabled>true</enabled>
                        <configuration>${project.basedir}/src/layers.xml</configuration>
                    </layers>
                </configuration>
                <executions>
                    <execution>
                        <id>build-info</id>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Baixa o swagger do endpoint informado -->
            <plugin>
                <groupId>com.googlecode.maven-download-plugin</groupId>
                <artifactId>download-maven-plugin</artifactId>
                <version>1.3.0</version>
                <executions>
                  <execution>
                    <id>generate-axway-openapi-file</id>
                    <!-- the wget goal actually binds itself to integration to get the ServerRunning -->
                    <phase>integration-test</phase>
                    <goals>
                      <goal>wget</goal>
                    </goals>
                    <configuration>
                      <url>http://localhost:8080/v3/api-docs</url>
                      <outputFileName>external_api.json</outputFileName>
                      <outputDirectory>config/all/deployment/</outputDirectory>
                      <skip>true</skip> <!-- troque para 'false' para habilitar o plugin -->
                    </configuration>
                  </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>8.0.1</version>
                <executions>
                    <execution>
                        <id>cve-dependency-check-local-only</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.8</version>
                <configuration>
                    <excludes>
                        <exclude>${sonar.coverage.exclusions}</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct-version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${lombok-mapstruct-binding.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
                <configuration>
                    <runOrder>random</runOrder>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.0.0-M7</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>${maven-dependency-plugin.version}</version>
				<executions>
					<execution>
						<id>opentelemetry-agent-download</id>
						<phase>package</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>io.opentelemetry.javaagent</groupId>
									<artifactId>opentelemetry-javaagent</artifactId>
									<version>1.24.0</version>
									<type>jar</type>
									<overWrite>false</overWrite>
									<outputDirectory>${project.build.directory}</outputDirectory>
									<destFileName>opentelemetry-javaagent.jar</destFileName>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>DEV</id>
            <properties>
                <spring.profiles.active>DEV</spring.profiles.active>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>HOM</id>
            <properties>
                <spring.profiles.active>HOM</spring.profiles.active>
            </properties>
        </profile>
        <profile>
            <id>PRD</id>
            <properties>
                <spring.profiles.active>PRD</spring.profiles.active>
            </properties>
        </profile>
        <profile>
            <id>LOCAL</id>
            <properties>
                <spring.profiles.active>LOCAL</spring.profiles.active>
            </properties>
            <activation>
                <property>
                    <name>LOCAL_ENVIRONMENT</name>
                </property>
            </activation>
            <repositories>
                <repository>
                    <id>bradex-maven-central</id>
                    <url>https://nexusrepository.bradesco.com.br:8443/repository/bradex-maven-central
                    </url>
                </repository>
                <repository>
                    <id>central</id>
                    <url>http://repo1.maven.org/maven2</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>bradex-maven-central</id>
                    <url>https://nexusrepository.bradesco.com.br:8443/repository/bradex-maven-central
                    </url>
                </pluginRepository>
                <pluginRepository>
                    <id>central</id>
                    <url>http://repo1.maven.org/maven2</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>7.1.1</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <distributionManagement>
        <repository>
            <id>${bamboo_inject_dominio}</id>
            <url>${repository.base}${repository_domain_name}${repository.maven.release}</url>
        </repository>
        <snapshotRepository>
            <id>${bamboo_inject_dominio}</id>
            <url>${repository.base}${repository_domain_name}${repository.maven.snapshot}</url>
        </snapshotRepository>
    </distributionManagement>

</project>
